import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { Flowbite, ThemeModeScript } from "flowbite-react";
import { flowbiteTheme } from "./theme";
import AppProvider from "@/lib/providers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "course website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-4728250862053645" crossorigin="anonymous"></script>
        <ThemeModeScript />
      </head>
      <Flowbite theme={{ theme: flowbiteTheme }}>
        <AppProvider>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white dark:bg-gray-900 text-gray-900 dark:text-gray-200`}
          >
            <div className="h-full">
              <main className="h-full w-full">{children}</main>
              <Toaster />
            </div>
          </body>
        </AppProvider>
      </Flowbite>
    </html>
  );
}
